### ISSUE TITLE
aqui também existe outra questão

### ISSUE THREAD

**Issue by SolarisSy** [KAYOKG/TCC-beta-version#3]
public Corretora(String idContrato, String data, String descricao, String observacao, String produto, float preco, float total, int quantidade, Comprador c, Vendedor v) {
        this.idContrato = idContrato;
        this.data = data;
        this.descricao = descricao;
        this.observacao = observacao;
        this.produto = produto;
        this.preco = preco;
        this.total = total;
        this.quantidade = quantidade;
        this.c = c;
        this.v = v;
    }

**Comment by KAYOKG** [comment]
Ok
